global using Microsoft.EntityFrameworkCore;
global using DataSaver.ApplicationCore.Entities;
global using Microsoft.Extensions.Logging;
global using DataSaver.ApplicationCore.Interfaces.IRepository;
global using DataSaver.Infrastructure.Data;
global using System.Linq.Expressions;
global using Microsoft.EntityFrameworkCore.Query;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;